# Generated by Django 6.0.2 on 2026-03-10 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_remove_user_created_by_user_company'),
        ('projects', '0002_alter_projectmembership_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.company'),
            preserve_default=False,
        ),
    ]
